# Generated by Django 4.2.6 on 2023-11-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIFapp', '0003_film_poster_path_film_tmdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
