# Generated by Django 4.2.6 on 2023-11-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIFapp', '0004_film_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='tmdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
