# Generated by Django 4.2.6 on 2023-11-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIFapp', '0006_alter_film_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='women_written',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
