# Generated by Django 4.2.6 on 2023-11-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIFapp', '0007_film_women_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
