# Generated by Django 4.2.6 on 2023-11-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIFapp', '0008_person_biography_person_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
