# Generated by Django 4.2.6 on 2023-12-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIFapp', '0012_film_woman_primary_star_alter_crew_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
