# Generated by Django 4.2.6 on 2023-12-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIFapp', '0013_alter_person_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
